### ISSUE TITLE
Extend to support docker-compose

### ISSUE THREAD

**Issue by faceleg** [lambci/ecs#1]
Currently my test suites run with docker-compose.

Opening this issue to facilitate discussion around what support for docker-compose might look like.

**Comment by faceleg** [comment]
My ideal user experience would be:
1. If I have included a `docker-compose-test.yml` file, LambCI uses that
2. Else use `Dockerfile.test`

**Comment by faceleg** [comment]
Adding `--privileged` to https://github.com/lambci/ecs/blob/master/runbuild.sh#L19 should do it

**Comment by mhart** [comment]
@faceleg is this still an issue? I don't really want to add `privileged` by default – users can always add it to their `LAMBCI_DOCKER_RUN_ARGS`

Can you give me some more insight into the current setup you've got working with LambCI+ECS?

**Comment by faceleg** [comment]
No, I have much better (faster) results rethinking my test/builds and modifying them to use a single container. Thanks for your time.

**Comment by bpinto** [comment]
I was interested in docker compose support. My tests require other services (database, memcache, redis) to run and their dependency is currently being handled by a docker compose config file.

**Comment by mhart** [comment]
@bpinto can you give me an example of what you need to enable docker compose support?

**Comment by bpinto** [comment]
From what I understood, in order to use this tool I need to run my tests inside a docker image generated using Dockerfile.test.

My current setup already run the tests inside a docker container but its dependencies (database, redis, etc) are on separate containers and linked using docker compose.

So, to use the current setup, I'd need to run docker inside of docker. I believe there is no need for that if it could support running a docker compose command instead.

**Comment by mhart** [comment]
@bpinto well Amazon ECS runs docker images, so by running docker compose in ECS you're going to have to be running docker inside docker anyway.

I think all you want to do is just override `docker.cmd` in your LambCI config. This is [passed to the ECS container as the env variable `LAMBCI_DOCKER_CMD`](https://github.com/lambci/lambci/blob/58734469e3e947bc89c5fe20b49562f370b099ef/actions/build.js#L302).

By default this is empty, so [it becomes `./runbuild.sh`](https://github.com/lambci/ecs/blob/master/common.sh#L13) which handles [the default `Dockerfile.test` flow](https://github.com/lambci/ecs/blob/master/runbuild.sh)

But you could set it to be whatever you like – a script that sets up and runs your docker compose config for example.

**Comment by bpinto** [comment]
Oh, that's sweet! I think that will do it! Thanks for the explanation!

**Comment by faceleg** [comment]
FWIW I had a similar use case to you, although simpler. My tests ran in one container with a Postgres instance in another.

I simplified it by running a small RDS instance for tests and having my test script create short lived dbs in that.
