### ISSUE TITLE
Build fails if Docker repository contains uppercase characters.

### ISSUE THREAD

**Issue by Dylanb-dev** [lambci/ecs#12]
When trying to build from a repo where there is an uppercase in the repo name, ecs throws the following error:

` invalid reference format: repository name must be lowercase`

Is there a way around this other than changing username/repo to be all lowercase?

edit: repository name (in EC2 container Registry) throws error

**Comment by mhart** [comment]
@lolcookie this is an error coming from Docker: https://github.com/docker/distribution/blob/master/reference/reference.go#L51

There's nothing LambCI (or even AWS's ECS) can do about that I'm afraid.

There shouldn't be any problem with Git repositories with uppercase names
